# fly.toml app configuration file generated for sist-conv-api on 2026-05-13T14:13:51-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sist-conv-api"
primary_region = "gru"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true

  # Inicia automáticamente cuando llega tráfico
  auto_start_machines = true

  # Detiene la máquina cuando no hay tráfico
  auto_stop_machines = "stop"

  # No mantener máquinas activas 24/7
  min_machines_running = 0

  # Opcional pero recomendado
  processes = ["app"]

  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/api/health"
    protocol = "http"

[[vm]]
  cpus = 1

  # Mucho más económico para un MVP NestJS
  memory_mb = 256
